{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  labels:
    app: frontend
  annotations:
    haproxy.org/forwarded-for: "true"
    haproxy.org/ingress.class: "{{ .Values.ingress.class }}"
    haproxy.org/backend-config-snippet: "compression algo gzip\ncompression type text/plain"
spec:
  ingressClassName: "{{ .Values.ingress.class }}"
  rules:
    - host: "{{ .Values.frontend.fqdn }}"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: frontend
                port:
                  number: 80
    - host: "www.{{ .Values.frontend.fqdn }}"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: frontend
                port:
                  number: 80
{{- end }}
