apiVersion: v1
kind: Secret
metadata:
  name: frontend
type: Opaque
stringData:
  DATABASE_HOST: "{{ .Values.database.host }}"
  DATABASE_PORT: "{{ .Values.database.port }}"
  DATABASE_USER: "{{ .Values.database.user }}"
  DATABASE_PASSWORD: "{{ .Values.database.password }}"
  DATABASE_NAME: "{{ .Values.database.name }}"
